bitzquad/bitzquad.com-2.0

components/home/ServiceCard.js
components/index.js
pages/index.js
styles/pages/_home-page.scss

🍡feature : service information section

---

components/home/OurTeam.js
components/home/OurTeamCard.js
components/home/ServiceCard.js
components/home/Testimonials.js
components/index.js
components/layouts/LayoutMain.js
pages/index.js
styles/pages/_home-page.scss

🍨 feature-our team section

---

.env
.gitignore
constants/Transmit.js
constants/schemas/Contact.js
constants/schemas/News.js
constants/schemas/Newsletter.js
middleware/mongodb.js
middleware/queryparser.js
middleware/request.js
package-lock.json
package.json
pages/api/Contact/index.js
pages/api/News/index.js
pages/api/Newsletter/[FName].js
pages/api/hello.js
pages/test.js

- Created schemas for contact details save.
- Newsletter email collect

feature-backendapi

---

components/home/Collaborate.js
components/home/OurPartners.js

- Fix bug in our partners <a> tag
- fix apostrophe error in collaborate.js 
-   [x] Project builds with `npm run build`
Windows 11 

hotfix: fix build errors - apos err & a tag err

---

pages/squad/index.js
styles/_tailwind.scss
tailwind.config.js

Jira issue: [B20-33](https://bitzquad-com.atlassian.net/browse/B20-33)
- add bz-container to squad page
Windows 11 

fix: squad page alignments 🐛

---

components/elements/Button.js
components/home/Collaborate.js
package-lock.json
package.json
styles/pages/_home-page.scss

Jira issue:[ [B20-33](https://bitzquad-com.atlassian.net/browse/B20-33)](https://bitzquad-com.atlassian.net/browse/B20-30?atlOrigin=eyJpIjoiZTRhZTJmMzQ2YzIzNDJjMWEzNzdmYzFlMjI1MGJhYjAiLCJwIjoiaiJ9)
- add bz-container to squad page
Windows 11 

fix B20-30 Collaborate section issue

---

tailwind.config.js

 fix dev build error

---

components/defaults/Footer.js
tailwind.config.js

Jira issue: 
[B20-26](https://bitzquad-com.atlassian.net/browse/B20-6)
- added footer 
- 
Windows 11 

 footer ok

---

components/defaults/Navbar.js
pages/index.js
styles/components/_sidemenu.scss

Jira issue: 
[B20-26](https://bitzquad-com.atlassian.net/browse/B20-26)
[B20-20](https://bitzquad-com.atlassian.net/browse/B20-29)
- add backdrop blur to sidemenu overlay 
- change font size in sidemenu navigation links
- fix responsive issue in desktop xl screens
Windows 11 

fix: sidemenu responsive and overlay 🐛

---

components/defaults/Footer.js
components/defaults/Navbar.js
constants/projects.js
pages/projects/[id].js
pages/projects/index.js
styles/components/_cursor.scss

Jira issue: [B20-37](https://bitzquad-com.atlassian.net/browse/B20-37)
- responsive - sm md lg <
- add initial animations
Windows 11 

Feature project page ✨ 

---

components/defaults/Navbar.js

Jira issue: 
[B20-38](https://bitzquad-com.atlassian.net/browse/B20-38)
- add scroll lock to scroll element
Windows 11 
scroll lock does not working in development mode (only work in production)

fix: page scrolling with sidemenu open 🐛 

---

components/layouts/LayoutMain.js
components/layouts/LayoutSubPages.js

- set smooth scroll to false
Windows 11 
-   [Next.js](https://nextjs.org/docs)
-   [Locomotive Scroll](https://github.com/locomotivemtl/locomotive-scroll)
scroll lock does not working in development mode (only work in production)

FIX: remove smooth scroll

---

pages/index.js

Comment testimonials from landing page

---

pages/squad/[id].js

- fix position image in member image
Windows 11 
-   [Next.js](https://nextjs.org/docs)
-   [Locomotive Scroll](https://github.com/locomotivemtl/locomotive-scroll)
scroll lock does not working in development mode (only work in production)

FIX: Stretch issue in member image 🐛

---

package-lock.json
pages/blog/[slug].js
pages/blog/index.js
posts/coding-best-practices.md
posts/ed-trends-waiting-to-say-hello-in-2023.md

- responsive - sm md lg <
Windows 11 

blog title extract ok

---

pages/blog/[slug].js

- add side content
Windows 11 
Have some ideas on mind with animations. will be implement in near future.

fix link extract issue

---

package-lock.json
package.json
pages/blog/[slug].js

Windows 11 
Have some ideas on mind with animations. will be implement in near future.

Fix MD sanitation issue

---

.env
components/layouts/LayoutMain.js
pages/404.js
pages/about/index.js
pages/blog/[slug].js
pages/blog/index.js
pages/comingsoon.js
pages/contact/index.js
pages/index.js
pages/projects/index.js
pages/squad/[id].js
pages/squad/index.js
posts/ed-trends-waiting-to-say-hello-in-2023.md

Windows 11 
Have some ideas on mind with animations. will be implement in near future.

fix meta image urls

---

posts/how-going-serverless-will-help-your-business.md

fix: url value bug

---

pages/blog/[slug].js

fix: og img in blog

---

pages/blog/[slug].js
pages/blog/index.js

- blog articles are no sorted according to published date
- Improved the way of displaying the read count
Preview - https://bitzquad-com-2-0-amber.vercel.app/blog

Blog articles sorting by date

---

components/home/OurTeam.js
components/index.js
pages/index.js

feat: Our leaders section

---

components/home/Landing.js

[PREVIEW URL](https://bitzquad-com-2-0-3l3de9hsd-geethakash.vercel.app/)

change landing description

---

.eslintrc.json
components/home/Landing.js
pages/_app.js
public/assets/js/flurry.js
styles/base/_base.scss
styles/components/_cursor.scss

fix: hide cursor follower in sm

---

constants/members.js

hotfix:member social links

---

components/home/OurPartners.js
components/home/OurTeam.js
components/home/ProjectSection.js
components/home/Services.js
styles/pages/_home-page.scss

- Topics are not consistent - Fixed
- Make “P” capital in “Our partners” - Fixed
- “Our Founders” > “Our Leaders” - Fixed
- Make “Read more” all capital or only the “R” (Services section) - Fixed
- Vertically align all paragraphs - Fixed
- Our founders, name and role texts are aligned to center - FIxed
- The right side looks blank. Shall we add the “Z” to the right side - Done

Bug: Landing page mistakes are fixed.

---

package-lock.json
pages/blog/index.js
posts/ed-trends-waiting-to-say-hello-in-2023.md
styles/pages/_blog-page.scss

- Not enough padding between Harsha’s name and the blogs below - Fixed
- Make the image on the right the same height as the content on the right - Fixed
- Add a space between “3” and “min read” (Ridmi's post) - Fixed
- Align all the content to the left - Fixed
- Font of the “BLOG” is different than the other fonts used in website- Fixed
- Bold paragraph - Fixed
- Put a small info on what the topic is about? Otherwise a lot of space gets wasted on some parts - Done

Bug: Blog page issues are fixed.

---

constants/projects.js
pages/projects/index.js

Bug: Project page alignment issues are fixed. 

---

posts/how-going-serverless-will-help-your-business.md
posts/social-media-addiction-and-dopamine-driven-feedback-loops.md
posts/storytelling-powerful-technique-for-transmitting-knowledge.md
posts/the-role-of-ai-in-education-sector.md

Fix: Updated few blog article titles

---

constants/members.js

- Removed Senuri's information

Remove Old Member : senuri 🌵 
